# Generated by Django 4.0.3 on 2022-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='assets\\img\x0condo.png', null=True, upload_to='imagenes'),
        ),
    ]
