# Generated by Django 4.0.3 on 2022-03-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0003_comentario_posts_usuario_delete_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='Mensaje',
            field=models.CharField(default='Escribe tu mensaje', max_length=100),
        ),
    ]
