# Generated by Django 4.0.3 on 2022-03-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0004_comentario_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='Mensaje',
        ),
    ]
