# Generated by Django 4.0.3 on 2022-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0006_posts_descripcion_posts_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='FechaDePublicacion',
            field=models.DateTimeField(),
        ),
    ]
