# Generated by Django 4.0.3 on 2022-04-26 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0008_alter_posts_fechadepublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Imagen',
            field=models.ImageField(default=datetime.datetime.now, upload_to='imagenes/'),
        ),
    ]
