# Generated by Django 4.0.3 on 2022-05-06 16:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0010_remove_posts_descripcion_posts_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='posts',
            name='Descripcion',
            field=ckeditor.fields.RichTextField(blank=True, default='Escribe Aqui', max_length=340, null=True),
        ),
    ]
