# Generated by Django 4.0.3 on 2022-05-06 20:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0011_remove_posts_descripcion_posts_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='FechaDePublicacion',
            new_name='fecha_de_publicacion',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='FechaDePublicacion',
            new_name='fecha_de_publicacion',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Imagen',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Descripcion',
        ),
        migrations.AddField(
            model_name='posts',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, default='Escribe Aqui', max_length=10000, null=True),
        ),
    ]
