# Generated by Django 4.0.3 on 2022-04-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='more_info',
            field=models.CharField(default='Escribe algo sobre ti', max_length=150),
        ),
    ]
